In [2]:
import numpy as np
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [2]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [3]:
python_list[0]

0

In [4]:
import sys
sys.getsizeof(python_list[0])

28

In [5]:
numpy_arr=np.arange(100)
numpy_arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
numpy_arr[0]

np.int64(0)

In [7]:
numpy_arr.nbytes

800

In [8]:
import time
size = 100000
l1 =list(range(size))
l2 = list(range(size))

strt_time=time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end_time=time.time()

print(end_time-strt_time)

0.0037043094635009766


In [9]:
n1=np.arange(size)
n2 = np.arange(size)

start_time=time.time()
n3 = n1+n2
end_time=time.time()

print(end_time-start_time)



0.0005338191986083984


In [10]:
rev_q1=np.array([10,13,11])
rev_q1.ndim

1

In [11]:
rev=np.array([[10,13,11],[14,12,11]])
rev.ndim

2

In [12]:
rev

array([[10, 13, 11],
       [14, 12, 11]])

In [13]:
rev[1,1]

np.int64(12)

In [14]:
rev[0,1]=14
rev

array([[10, 14, 11],
       [14, 12, 11]])

In [15]:
rev.dtype

dtype('int64')

In [16]:
rev=np.array([[10,13,11],[14,12,11]],dtype=np.float64)
rev.ndim

2

In [17]:
a=np.array([6,7,8,9])
a[0:2]

array([6, 7])

In [18]:
a[2:]

array([8, 9])

In [19]:
a[-2:]

array([8, 9])

In [20]:
b=np.array([[1,2,3],
           [4,5,6],
           [7,8,9]])

b[1,2]

np.int64(6)

In [21]:
b[2,0:2]

array([7, 8])

In [22]:
b[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [3]:
#customer ID and name

c=np.array([
        [101,'janaki'],
        [102,'raam'],
        [103,'ravi']
])



In [4]:
#customer ID, purchase amount and date

d=np.array([
            [101, 205.50,'20-6-2025'],
            [102,200.00,'20-3-2025'],
            [103,207.25,'30-4-2026']
])

In [5]:
np.hstack((c,d))

array([['101', 'janaki', '101', '205.5', '20-6-2025'],
       ['102', 'raam', '102', '200.0', '20-3-2025'],
       ['103', 'ravi', '103', '207.25', '30-4-2026']], dtype='<U32')

In [6]:
np.vstack((c,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [7]:
e=np.array([
           [104,'venkat'],
        [105,'ravi'],
        [106,'jaya']
])

In [9]:
np.hstack((c,e))

array([['101', 'janaki', '104', 'venkat'],
       ['102', 'raam', '105', 'ravi'],
       ['103', 'ravi', '106', 'jaya']], dtype='<U21')

In [11]:
np.hsplit(d,[2])

[array([['101', '205.5'],
        ['102', '200.0'],
        ['103', '207.25']], dtype='<U32'),
 array([['20-6-2025'],
        ['20-3-2025'],
        ['30-4-2026']], dtype='<U32')]

In [12]:
f,g=np.hsplit(d,[2])

In [13]:
f

array([['101', '205.5'],
       ['102', '200.0'],
       ['103', '207.25']], dtype='<U32')

In [14]:
g

array([['20-6-2025'],
       ['20-3-2025'],
       ['30-4-2026']], dtype='<U32')

In [15]:
np.vsplit(d,[2])

[array([['101', '205.5', '20-6-2025'],
        ['102', '200.0', '20-3-2025']], dtype='<U32'),
 array([['103', '207.25', '30-4-2026']], dtype='<U32')]

In [16]:
montly_expense= np.array([33,32,45,22,31,22])
result = montly_expense >= 31

In [17]:
result 

array([ True,  True,  True, False,  True, False])

In [18]:
montly_expense[result]

array([33, 32, 45, 31])

In [19]:
montly_expense.max()

np.int64(45)

In [20]:
montly_expense.min()

np.int64(22)

In [21]:
np.argmax(montly_expense)

np.int64(2)

In [22]:
d

array([['101', '205.5', '20-6-2025'],
       ['102', '200.0', '20-3-2025'],
       ['103', '207.25', '30-4-2026']], dtype='<U32')

In [23]:
d[:,1]

array(['205.5', '200.0', '207.25'], dtype='<U32')

In [24]:
np.argmax(d[:,1].astype(float))

np.int64(2)

In [25]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[:2, 1:])

[[20 30]
 [50 60]]


In [26]:
j=np.arange(10)
j

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])